apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-juniolima
  namespace: juniolima
spec:
  storageClassName: default-storage-class-juniolima
  selector:
    matchLabels:
      namespace: juniolima
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: project2-pv2-juniolima
