apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
spec:
  selector:
    app: juniolima-playlist-recommender
  ports:
    - protocol: TCP
      port: 52039
      targetPort: 5000
  type: ClusterIP