apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
  namespace: juniolima
spec:
  selector:
    app: juniolima-playlist-recommender
  ports:
    - protocol: TCP
      port: 52039
      targetPort: 5000
      nodePort: 52039
  type: NodePort